services:
	db:
		image: mysql
		restrat: always
		container_name: ss-db
		environment: 
			MYSQL_ROOT_PASSWORD: yg-pass
			MYSQL_DATABASE: ss-db
			MYSQL_USER: ygunes
			MYSQL_PASSWORD: y-suf
		ports:
			- '3306:3306'